### PR TITLE
docs: updated README

### PR DESCRIPTION
**Pull request by art1373**
I updated the readme to be a little easier to understand.

This PR closes issue #51

### CODE REVIEW

**Review by amerllica — DISMISSED** [review]
Thanks for your help.

**Comment by amerllica** [comment]
Dear @art1373, Thanks for your help, please resolve the conflict.

**Comment by art1373** [comment]
@amerllica done. please review it and if any problem let me know thanks. :)

**Review by amerllica — APPROVED** [review]

**Comment by amerllica** [comment]
Dear @art1373, Sorry for late.

**Pull request merged**
